spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb2
    username: todouser
    password:
    driver-class-name: org.postgresql.Driver

#mybatis:
#  mapper-locations: classpath:mappers/*.xml  # MyBatis?????(XML)???????
#  configuration:
#    map-underscore-to-camel-case: true  # ????????????????????
#  type-aliases-package: com.example.domain  # ????????????JavaBeans??????